api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: :80

  websecure:
    address: :443
    http:
      middlewares:
        - security-headers@file
    transport:
      respondingTimeouts:
        readTimeout: 0
        writeTimeout: 0
        idleTimeout: 300
  metrics:
    address: :8000

metrics:
  prometheus: 
    entryPoint: metrics
    addEntryPointsLabels: true

providers:
  docker:
    exposedByDefault: false
    network: dmz-internal
  file:
    directory: /dyn

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /letsencrypt/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web

log:
  level: trace
