volumes:
  vault_data:
  db_data:


networks:
  dmz-internal:
    external: true
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.2.0/28

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: pass_vaultwarden
    restart: always
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: ${SMTP_SECURITY}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@pass_postgres/vaultwarden
      DOMAIN: https://${DOMAIN} # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "false" # Deactivate this with "false" after you have created your account so that no strangers can register
      ORG_EVENTS_ENABLED: ${ORG_EVENTS_ENABLED}
      EMAIL_CHANGE_ALLOWED: ${EMAIL_CHANGE_ALLOWED}
      INVITATION_ORG_NAME: ${INVITATION_ORG_NAME}
      SIGNUPS_DOMAINS_WHITELIST: ${SIGNUPS_DOMAINS_WHITELIST}
      ORG_CREATTION_USERS: oehring@ngenn.net,hansche@ngenn.net
      HIBP_API_KEY: ${HIBP_API_KEY}
      EMERGENCY_ACCESS_ALLOWED: "false"
      PASSWORD_HINTS_ALLOWED: "false"
      DISABLE_2FA_REMEMBER: "true"
      SIGNUPS_VERIFY: ${SIGNUPS_VERIFY}
      _ENABLE_YUBICO: "false"
      _ENABLE_DUO: "false"
      _ENABLE_EMAIL_2FA: "false"
      ENFORCE_SINGLE_ORG_WITH_RESET_PW_POLICY: "true"
    volumes:
      - vault_data:/data # the path before the : can be changed
    labels:
      - traefik.enable=true
      - traefik.http.routers.pass.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pass.entrypoints=websecure
      - traefik.http.routers.pass.tls.certresolver=letsencrypt
      - traefik.http.services.pass.loadbalancer.server.port=80
      - traefik.http.routers.pass-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.pass-http.entrypoints=web
      - traefik.http.routers.pass-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
    networks:
      - dmz-internal
      - app

  db:
    container_name: pass_postgres
    restart: unless-stopped
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vaultwarden
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app
