services:
  db:
    container_name: crm_postgres
    restart: unless-stopped
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: espocrm
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app

  espocrm:
    image: espocrm/espocrm:latest
    container_name: crm_espo
    depends_on:
      - db
    environment:
      ESPOCRM_DATABASE_PLATFORM: Postgresql
      ESPOCRM_DATABASE_HOST: db
      ESPOCRM_DATABASE_USER: ${DB_USER}
      ESPOCRM_DATABASE_PASSWORD: ${DB_PASSWORD}
      ESPOCRM_ADMIN_USERNAME: ${ESPOCRM_ADMIN_USERNAME}
      ESPOCRM_ADMIN_PASSWORD: ${ESPOCRM_ADMIN_PASSWORD}
      ESPOCRM_SITE_URL: https://${DOMAIN}
      ESPOCRM_CONFIG_LOGGER_LEVEL: DEBUG
    volumes:
      - espo_data:/var/www/html
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.espocrm-app.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.espocrm-app.entrypoints=websecure
      - traefik.http.routers.espocrm-app.tls=true
      - traefik.http.routers.espocrm-app.tls.certresolver=letsencrypt
    networks:
      - app
      - dmz-internal

  espocrm-daemon:
    image: espocrm/espocrm:latest
    container_name: production_espo_daemon
    depends_on:
      - db
    volumes:
      - espo_data:/var/www/html
    restart: unless-stopped
    entrypoint: docker-daemon.sh
    networks:
      - app

  espocrm-websocket:
    image: espocrm/espocrm:latest
    container_name: crm_espo_websocket
    depends_on:
      - db
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: true
      ESPOCRM_CONFIG_WEB_SOCKET_URL: wss://${DOMAIN}/ws
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: tcp://*:7777
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: tcp://espocrm-websocket:7777
    volumes:
      - espo_data:/var/www/html
    restart: always
    entrypoint: docker-websocket.sh
    labels:
      - traefik.enable=true
      - traefik.http.routers.espocrm-ws.rule=Host(`${DOMAIN}`) && PathPrefix(`/ws`)
      - traefik.http.routers.espocrm-ws.entrypoints=websecure
      - traefik.http.routers.espocrm-ws.tls=true
      - traefik.http.routers.espocrm-ws.tls.certresolver=letsencrypt
    networks:
      - app
      - dmz-internal

networks:
  dmz-internal:
    external: true
  app:


volumes:
  postgres_data:
  espo_data:
