services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: git_gitlab
    restart: unless-stopped
    hostname: ${DOMAIN}
    ports:
      - published: 22
        target: 22
      # env_file:
      #   - .e
      # entrypoint: sleep 1000
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${DOMAIN}'
        registry_external_url 'https://${REGISTRY_DOMAIN}'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 80
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'

        gitlab_rails['smtp_enable'] = ${SMTP_ENABLED}
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "SMTP_DOMAIN"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'

        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails["omniauth_allow_single_sign_on"] = ["openid_connect"]
        gitlab_rails["omniauth_auto_sign_in_with_provider"] = false
        gitlab_rails['omniauth_providers'] = [

          {
            name: "openid_connect",
            label: "${OIDC_LABEL}", # optional label for login button, defaults to "Openid Connect"
            args: {
              name: "openid_connect",
              scope: ["openid", "profile", "email"],
              response_type: "code",
              issuer:  "${OIDC_ISSUER}",
              client_auth_method: "query",
              discovery: true,
              uid_field: "preferred_username",
              client_options: {
                identifier: "${OIDC_CLIENT_ID}",
                secret: "${OIDC_CLIENT_SECRET}",
                redirect_uri: "https://${DOMAIN}/users/auth/openid_connect/callback"
              }
            }
          }
        ]

    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${DOMAIN}`) || Host(`${REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
      - "traefik.http.services.cloud-https.loadbalancer.server.port=80"
      - "docker-volume-backup.stop-during-backup=true"

    networks:
      - dmz-internal

networks:
  dmz-internal:
    external: true

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
